### ISSUE TITLE
gentoo-update update full

### ISSUE THREAD

**Issue by hangint3n** [Lab-Brat/gentoo_update#30] opened 2023-12-01 14:56 UTC
Where do I put my API key?

**Comment by Lab-Brat** [comment] 2023-12-01 15:11
Follow these steps to use Sendgrid API:

Install sendgrid python library (from GURU):
```
# unmask library and it's dependencies
dev-python/sendgrid ~amd64
dev-python/python-http-client ~amd64
dev-python/starkbank-ecdsa ~amd64

# install lib
sudo emerge --ask dev-python/sendgrid
```

Add API key and other info to env variables
```
export SENDGRID_TO='<to_address>'
export SENDGRID_FROM='<from_address>'
export SENDGRID_API_KEY='<api_key>'
```

Send the report (if the update was done already)
```
gentoo-update report --send email
```

**Comment by Lab-Brat** [comment] 2023-12-01 15:12
Will add this info to README later this week 🙂

**Comment by hangint3n** [comment] 2023-12-01 15:18
Awesome, thanks for the update!

I plan to run this as a cronjob....

Looking forward to good results.

**Comment by hangint3n** [comment] 2023-12-11 18:25
Two things can you put gentoo-update update and report is the same string? 'Cause I couldn't make it work.  Second, I was semi-successful with gentoo-update report -s email, but I didn't receive email and not in my spam folders?

**Comment by hangint3n** [comment] 2023-12-13 17:15
Can mode and report be run from gentoo-update? I tried and it gave me an
error.


bbox /home/hangint3n # gentoo-update update -m full -s email
usage: gentoo-update [-h] {update,report,version} ...
gentoo-update: error: unrecognized arguments: -s email
bbox /home/hangint3n # gentoo-update update -m full report -s email
usage: gentoo-update [-h] {update,report,version} ...
gentoo-update: error: unrecognized arguments: report -s email
bbox /home/hangint3n #

**Comment by Lab-Brat** [comment] 2023-12-13 18:25
> can you put gentoo-update update and report is the same string?

You can just use **&&** to connect them 🙂 
```
gentoo-update update -m full && gentoo-update report -s email
```

> but I didn't receive email and not in my spam folders?

The issue is probably somewhere on the Sendgrid side...
Does your output looks like this?
```
2959553524c9 / # gentoo-update report -s email
email was sent successfully!
```

Also, is the report correctly generated? It should look something like this
```
2959553524c9 / # gentoo-update report
==========> Gentoo Update Report <==========
update status: SUCCESS
processed packages:
--- sys-libs/glibc 2.37-r3:2.2->2.37-r7:2.2
--- app-arch/libarchive ->3.7.1:0/13
--- app-crypt/rhash ->1.4.3
--- dev-libs/libuv ->1.46.0:0/1
--- dev-util/meson 1.1.1->1.2.3
--- dev-libs/jsoncpp ->1.9.5:0/25
--- dev-util/cmake ->3.27.7
--- net-libs/nghttp2 ->1.57.0:0/1.14
--- net-misc/curl 8.1.2->8.4.0

Disk Usage Stats:
Mount Point /
Free Space 269G => 269G
Used Space 161G => 161G
Used (%) 38% => 38%
```

**Comment by hangint3n** [comment] 2023-12-13 18:29
Yup both of those outputs look like what I received running gentoo-update report -s email.  Using "&&" works for me.  Thanks for the prompt reply.

**Comment by Lab-Brat** [comment] 2023-12-13 18:33
Then it could be 2 things:
1. You have a very secure email provider that just doesn't deliver emails flagged as spam, for instance ProtonMail might do that.
2. There is some misconfiguration in Sendgrid.

In the future (maybe in 1-2 months) I am planning to a add a simpler mechanism to send out emails, people have been complaining about Sendgrid a lot 😓

**Comment by hangint3n** [comment] 2023-12-13 18:48
I've read that come February Gmail is going to make change to there secure mailing that might make it more difficult to use.

**Comment by hangint3n** [comment] 2023-12-15 13:32
Weirdly I ran the command gentoo-update report -s email

And I got a notification of a successful send, but this time I never got
the email. Just to be sure I did check the spam folder.

**Comment by Lab-Brat** [comment] 2024-03-10 12:14
Finally got around to experiment with local SMTP relays.

In the end I've decided not to implement the email sending mechanism into `gentoo-update` because it already works really well with relay tools such as `msmtp`, `mailx` or `sendmail`.

It could be a bit of a hassle to set it up, but afterwards you can just pipe the output from the reporter to the relay to send the email:
```bash
echo -e "Subject: Gentoo Update Report\n\n$(gentoo-update report)" | msmtp -a default <target-email>@gmail.com
```

There are a lot of info out there how to set up Gmail (or other email providers...) with aforementioned tools, and I also wrote a blog post about it (Link [here](https://labbrat.net/blog/send_emails_from_terminal/)).

In the future I will probably implement report formatting in HTML to make it look a bit better, but for now I'm considering all email-related issues resolved. Closing the issue now 🐱

**Closed as completed by Lab-Brat** 2024-03-10 12:14 UTC
Labels: documentation
